#!/usr/bin/env sh                                                                                                      
                                                                                                                       
/app/script.sh $CALDAV_URL $CALDAV_USER $CALDAV_PASS $CALDAV_CALENDAR_URL 